{{- range .Values.nodes }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .wave | quote }}
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: victoriametrics
      instance: {{ .name }}
  template:
    metadata:
      labels:
        app: victoriametrics
        instance: {{ .name }}
    spec:
      terminationGracePeriodSeconds: 60
      hostAliases:
      - ip: "140.82.121.4"
        hostnames: ["github.com"]
      containers:
      - name: vm
        image: "victoriametrics/victoria-metrics:{{ $.Values.imageTag }}"
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: data
            mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
---
{{- end }}
